### ISSUE TITLE
[FR] Spamtrap for spambots

### ISSUE THREAD

**Issue by DubhAd** [Blade2021/Sherlock#17]
**Is your feature request related to a problem? Please describe.**
Spammers turn up and drop the same message in multiple channels, usually every channel.

**Describe the solution you'd like**
A spam trap channel, such as `#ban_me`. If somebody posts there, and they don't have the radiant role, then they're automatically muted for a given time window (an hour?).

**Describe alternatives you've considered**
Other options may include:
* If somebody posts the same message in multiple channels in a small time window they get automatically muted.
* A way of people easily reporting spam

**Additional context**
_Nothing to see here_

**Comment by SirGoodenough** [comment]
More information in the message thread started here:
[DrZzs Radiants message thread](https://discord.com/channels/469330414121517056/469558321590960150/882684363874123806)

**Comment by Blade2021** [comment]
I'm gonna have to close this for now as it seems spammers don't go to every channel so it would be inefficient.
