### ISSUE TITLE
[FR] mute command confusing

### ISSUE THREAD

**Issue by SirGoodenough** [Blade2021/Sherlock#19]
**Is your feature request related to a problem? Please describe.**

So using the ' !mute DUID ' results in no response from Sherlock.  Also using that command the docs are not clear on how to turn mute off... 
 
Also the logs have a space for reason, but I do not recall that the documentation mentioned ability to add a reason.

**Describe the solution you'd like**

Update command to respond with a message or icon on invocation.  (NOTE: I now see that something shows in the logs, found that later)

Document the procedure to un-mute from the ' !mute DUID ' command.

Clarify the reason, does it exist, if so document it...  if not fine but why is it in the log.

**Describe alternatives you've considered**

To unmute, I did another mute with a timer, doesn't seem like the right way but it worked.

**Additional context**
https://discord.com/channels/469330414121517056/717069963357323326/904835815560081428

**Comment by Blade2021** [comment]
The mute command is no longer supported by Sherlock as Discord introduced the Timeout feature which supports this feature by default.
