### ISSUE TITLE
[FR] Auto .topic trigger

### ISSUE THREAD

**Issue by SirGoodenough** [Blade2021/Sherlock#21]
**Is your feature request related to a problem? Please describe.**
Channels such as spam channels and others could use occasional intervention to help people understand what they are for, and they don't click the topic button themselves.

**Describe the solution you'd like**
I would like the ability to have Sherlock post the .topic results after a electable number of posts.  So the Mod could set it that every 20, 40, or 60 posts in a channel the .topic is triggered.  Electable by channel.  A time schedule would also work, once a week or day kind of thing.

**Describe alternatives you've considered**
I currently do this on a couple of channels when I remember, would like it automated for say General every 40 or so and botspam more often.  Time schedule also works.

**Additional context**

**Comment by Blade2021** [comment]
I don't think this fits the idea behind Sherlock.
