### ISSUE TITLE
[FR] Allow Whitelist to have Note for Server Name

### ISSUE THREAD

**Issue by jazakzewski** [Blade2021/Sherlock#24]
**Is your feature request related to a problem? Please describe.**

Cannot easily determine which servers are added to the whitelist as it is only based on ID

**Describe the solution you'd like**

Add field for a note to maintain the server name as a reference

**Describe alternatives you've considered**

**Additional context**

**Comment by Blade2021** [comment]
I'm working on this now.  Just waiting for Discord to propagate so I can test it.

**Comment by Blade2021** [comment]
Done.
