### ISSUE TITLE
[FR] Instant delete on blacklisted word

### ISSUE THREAD

**Issue by ikifar2012** [Blade2021/Sherlock#28]
### Is your feature request related to a problem? Please describe.

When a user says a blacklisted word, the bot gives them time to edit the message before deleting it, this can cause issues in some servers

### Describe the solution you'd like

It would be great if you gave the server admin the choice to instant delete blacklisted word's

### Describe alternatives you've considered

A customizable duration before deletion set by the server admin would also be great

**Comment by Blade2021** [comment]
I'm closing this due to excessive age and Discord has implemented the AutoMod which will support this function better.
