### ISSUE TITLE
Add BOT response after ModRole Command is Executed [FR] 

### ISSUE THREAD

**Issue by SirGoodenough** [Blade2021/Sherlock#7]
**Is your feature request related to a problem? Please describe.**
When using the ModRole Commands, sherlock does not give you feedbck so you don't know if the command took.

**Describe the solution you'd like**
Response from the BOT.  I think the best response would be the output from the getModRoles command, but even an emoji response would work to ley you know the command was executed.

**Describe alternatives you've considered**
Typing getModRoles myself after every change to see the result.

**Additional context**

**Comment by Blade2021** [comment]
Done.
